# Generated by retrobeam-linux-stage3-v3.sh
# RetroBeam Milestone B: native support libraries.
# Source membership mirrors the last proven bridge archives,
# with the Windows libscg transport replaced by Linux SG.

if(NOT UNIX OR WIN32)
    message(FATAL_ERROR "retrobeam-native-libs.cmake is for native POSIX builds")
endif()

set(RB_NATIVE_COMMON_INCLUDES
    "${CMAKE_CURRENT_BINARY_DIR}/generated"
    "${CMAKE_CURRENT_SOURCE_DIR}/include"
    "${SCHILY_ROOT}/include"
    "${SCHILY_ROOT}/libscg"
    "${SCHILY_ROOT}/libscgcmd"
    "${SCHILY_ROOT}/librscg"
    "${SCHILY_ROOT}/libedc"
    "${SCHILY_ROOT}/libcdrdeflt"
    "${SCHILY_ROOT}/libdeflt"
    "${SCHILY_ROOT}/libschily"
    "${SCHILY_ROOT}/cdrecord"
)

add_library(retrobeam_scgcmd STATIC
    "${SCHILY_ROOT}/libscgcmd/buffer.c"
    "${SCHILY_ROOT}/libscgcmd/inquiry.c"
    "${SCHILY_ROOT}/libscgcmd/modes.c"
    "${SCHILY_ROOT}/libscgcmd/modesense.c"
    "${SCHILY_ROOT}/libscgcmd/read.c"
    "${SCHILY_ROOT}/libscgcmd/readcap.c"
    "${SCHILY_ROOT}/libscgcmd/ready.c"
)
target_include_directories(retrobeam_scgcmd PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_scgcmd PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_scgcmd PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

add_library(retrobeam_rscg STATIC
    "${SCHILY_ROOT}/librscg/scsi-remote.c"
)
target_include_directories(retrobeam_rscg PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_rscg PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_rscg PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

add_library(retrobeam_scg STATIC
    "${SCHILY_ROOT}/libscg/scsitransp.c"
    "${SCHILY_ROOT}/libscg/scsihack.c"
    "${SCHILY_ROOT}/libscg/scsiopen.c"
    "${SCHILY_ROOT}/libscg/scgsettarget.c"
    "${SCHILY_ROOT}/libscg/scsierrs.c"
    "${SCHILY_ROOT}/libscg/scgtimes.c"
    "${SCHILY_ROOT}/libscg/scsihelp.c"
    "${SCHILY_ROOT}/libscg/scsiopts.c"
    "${SCHILY_ROOT}/libscg/rdummy.c"
)
target_include_directories(retrobeam_scg PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_scg PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_scg PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

# RETROBEAM_LINUX_SCSIHACK_SG_V11
# scsihack.c owns scg_std_ops and textually selects scsi-linux-sg.c.
# Preinclude suppresses only the obsolete direct-/dev/hd* ATAPI subtransport.
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_compile_options(retrobeam_scg PRIVATE
        "-include"
        "${CMAKE_CURRENT_SOURCE_DIR}/retrobeam-linux-sg-preinclude.h"
    )
endif()


add_library(retrobeam_edc_ecc STATIC
    "${SCHILY_ROOT}/libedc/edc_ecc.c"
)
target_include_directories(retrobeam_edc_ecc PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_edc_ecc PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_edc_ecc PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

add_library(retrobeam_cdrdeflt STATIC
    "${SCHILY_ROOT}/libcdrdeflt/cdrdeflt.c"
)
target_include_directories(retrobeam_cdrdeflt PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_cdrdeflt PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_cdrdeflt PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

add_library(retrobeam_deflt STATIC
    "${SCHILY_ROOT}/libdeflt/default.c"
)
target_include_directories(retrobeam_deflt PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_deflt PRIVATE
    USE_LARGEFILES
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
)
set_target_properties(retrobeam_deflt PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

add_library(retrobeam_schily STATIC
    "${SCHILY_ROOT}/libschily/stdio/cvmod.c"
    "${SCHILY_ROOT}/libschily/stdio/dat.c"
    "${SCHILY_ROOT}/libschily/stdio/fcons.c"
    "${SCHILY_ROOT}/libschily/stdio/fdown.c"
    "${SCHILY_ROOT}/libschily/stdio/fdup.c"
    "${SCHILY_ROOT}/libschily/stdio/ffileread.c"
    "${SCHILY_ROOT}/libschily/stdio/ffilewrite.c"
    "${SCHILY_ROOT}/libschily/stdio/fgetaline.c"
    "${SCHILY_ROOT}/libschily/stdio/fgetline.c"
    "${SCHILY_ROOT}/libschily/stdio/fgetstr.c"
    "${SCHILY_ROOT}/libschily/stdio/file_getraise.c"
    "${SCHILY_ROOT}/libschily/stdio/file_raise.c"
    "${SCHILY_ROOT}/libschily/stdio/fileclose.c"
    "${SCHILY_ROOT}/libschily/stdio/fileluopen.c"
    "${SCHILY_ROOT}/libschily/stdio/fileopen.c"
    "${SCHILY_ROOT}/libschily/stdio/filemopen.c"
    "${SCHILY_ROOT}/libschily/stdio/filepos.c"
    "${SCHILY_ROOT}/libschily/stdio/fileread.c"
    "${SCHILY_ROOT}/libschily/stdio/filereopen.c"
    "${SCHILY_ROOT}/libschily/stdio/fileseek.c"
    "${SCHILY_ROOT}/libschily/stdio/filesize.c"
    "${SCHILY_ROOT}/libschily/stdio/filestat.c"
    "${SCHILY_ROOT}/libschily/stdio/filewrite.c"
    "${SCHILY_ROOT}/libschily/stdio/flag.c"
    "${SCHILY_ROOT}/libschily/stdio/flush.c"
    "${SCHILY_ROOT}/libschily/stdio/fpipe.c"
    "${SCHILY_ROOT}/libschily/stdio/getdelim.c"
    "${SCHILY_ROOT}/libschily/stdio/niread.c"
    "${SCHILY_ROOT}/libschily/stdio/niwrite.c"
    "${SCHILY_ROOT}/libschily/stdio/nixread.c"
    "${SCHILY_ROOT}/libschily/stdio/nixwrite.c"
    "${SCHILY_ROOT}/libschily/stdio/openfd.c"
    "${SCHILY_ROOT}/libschily/stdio/peekc.c"
    "${SCHILY_ROOT}/libschily/stdio/fcons64.c"
    "${SCHILY_ROOT}/libschily/stdio/fdup64.c"
    "${SCHILY_ROOT}/libschily/stdio/fileluopen64.c"
    "${SCHILY_ROOT}/libschily/stdio/fileopen64.c"
    "${SCHILY_ROOT}/libschily/stdio/filemopen64.c"
    "${SCHILY_ROOT}/libschily/stdio/filepos64.c"
    "${SCHILY_ROOT}/libschily/stdio/filereopen64.c"
    "${SCHILY_ROOT}/libschily/stdio/fileseek64.c"
    "${SCHILY_ROOT}/libschily/stdio/filesize64.c"
    "${SCHILY_ROOT}/libschily/stdio/filestat64.c"
    "${SCHILY_ROOT}/libschily/stdio/openfd64.c"
    "${SCHILY_ROOT}/libschily/abspath.c"
    "${SCHILY_ROOT}/libschily/astoi.c"
    "${SCHILY_ROOT}/libschily/astoll.c"
    "${SCHILY_ROOT}/libschily/astoul.c"
    "${SCHILY_ROOT}/libschily/astoull.c"
    "${SCHILY_ROOT}/libschily/basename.c"
    "${SCHILY_ROOT}/libschily/breakline.c"
    "${SCHILY_ROOT}/libschily/checkerr.c"
    "${SCHILY_ROOT}/libschily/comerr.c"
    "${SCHILY_ROOT}/libschily/fcomerr.c"
    "${SCHILY_ROOT}/libschily/gtcomerr.c"
    "${SCHILY_ROOT}/libschily/fgtcomerr.c"
    "${SCHILY_ROOT}/libschily/chown.c"
    "${SCHILY_ROOT}/libschily/cmpbytes.c"
    "${SCHILY_ROOT}/libschily/cmpmbytes.c"
    "${SCHILY_ROOT}/libschily/cmpnullbytes.c"
    "${SCHILY_ROOT}/libschily/dirent.c"
    "${SCHILY_ROOT}/libschily/dirname.c"
    "${SCHILY_ROOT}/libschily/diropen.c"
    "${SCHILY_ROOT}/libschily/dlfcn.c"
    "${SCHILY_ROOT}/libschily/eaccess.c"
    "${SCHILY_ROOT}/libschily/error.c"
    "${SCHILY_ROOT}/libschily/gterror.c"
    "${SCHILY_ROOT}/libschily/faccessat.c"
    "${SCHILY_ROOT}/libschily/fchdir.c"
    "${SCHILY_ROOT}/libschily/fchmodat.c"
    "${SCHILY_ROOT}/libschily/fchownat.c"
    "${SCHILY_ROOT}/libschily/fconv.c"
    "${SCHILY_ROOT}/libschily/fdopendir.c"
    "${SCHILY_ROOT}/libschily/fexec.c"
    "${SCHILY_ROOT}/libschily/fillbytes.c"
    "${SCHILY_ROOT}/libschily/findinpath.c"
    "${SCHILY_ROOT}/libschily/findbytes.c"
    "${SCHILY_ROOT}/libschily/findline.c"
    "${SCHILY_ROOT}/libschily/fnmatch.c"
    "${SCHILY_ROOT}/libschily/format.c"
    "${SCHILY_ROOT}/libschily/fpoff.c"
    "${SCHILY_ROOT}/libschily/fprformat.c"
    "${SCHILY_ROOT}/libschily/fstatat.c"
    "${SCHILY_ROOT}/libschily/fstatat64.c"
    "${SCHILY_ROOT}/libschily/fstream.c"
    "${SCHILY_ROOT}/libschily/futimens.c"
    "${SCHILY_ROOT}/libschily/futimesat.c"
    "${SCHILY_ROOT}/libschily/getargs.c"
    "${SCHILY_ROOT}/libschily/getav0.c"
    "${SCHILY_ROOT}/libschily/geterrno.c"
    "${SCHILY_ROOT}/libschily/getexecpath.c"
    "${SCHILY_ROOT}/libschily/getfp.c"
    "${SCHILY_ROOT}/libschily/getgrent.c"
    "${SCHILY_ROOT}/libschily/getdtablesize.c"
    "${SCHILY_ROOT}/libschily/getdomainname.c"
    "${SCHILY_ROOT}/libschily/gethostid.c"
    "${SCHILY_ROOT}/libschily/gethostname.c"
    "${SCHILY_ROOT}/libschily/getpagesize.c"
    "${SCHILY_ROOT}/libschily/getlogin.c"
    "${SCHILY_ROOT}/libschily/getnum.c"
    "${SCHILY_ROOT}/libschily/getxnum.c"
    "${SCHILY_ROOT}/libschily/gettnum.c"
    "${SCHILY_ROOT}/libschily/getxtnum.c"
    "${SCHILY_ROOT}/libschily/getperm.c"
    "${SCHILY_ROOT}/libschily/getpwent.c"
    "${SCHILY_ROOT}/libschily/getnstimeofday.c"
    "${SCHILY_ROOT}/libschily/gettimeofday.c"
    "${SCHILY_ROOT}/libschily/gid.c"
    "${SCHILY_ROOT}/libschily/handlecond.c"
    "${SCHILY_ROOT}/libschily/jsdprintf.c"
    "${SCHILY_ROOT}/libschily/jsprintf.c"
    "${SCHILY_ROOT}/libschily/jssnprintf.c"
    "${SCHILY_ROOT}/libschily/jssprintf.c"
    "${SCHILY_ROOT}/libschily/gtprintf.c"
    "${SCHILY_ROOT}/libschily/kill.c"
    "${SCHILY_ROOT}/libschily/lchmod.c"
    "${SCHILY_ROOT}/libschily/linkat.c"
    "${SCHILY_ROOT}/libschily/lutimens.c"
    "${SCHILY_ROOT}/libschily/lxchdir.c"
    "${SCHILY_ROOT}/libschily/match.c"
    "${SCHILY_ROOT}/libschily/matchl.c"
    "${SCHILY_ROOT}/libschily/matchmb.c"
    "${SCHILY_ROOT}/libschily/matchmbl.c"
    "${SCHILY_ROOT}/libschily/matchw.c"
    "${SCHILY_ROOT}/libschily/matchwl.c"
    "${SCHILY_ROOT}/libschily/movebytes.c"
    "${SCHILY_ROOT}/libschily/movecbytes.c"
    "${SCHILY_ROOT}/libschily/mkdirat.c"
    "${SCHILY_ROOT}/libschily/mkdirs.c"
    "${SCHILY_ROOT}/libschily/mkfifo.c"
    "${SCHILY_ROOT}/libschily/mkfifoat.c"
    "${SCHILY_ROOT}/libschily/mkgmtime.c"
    "${SCHILY_ROOT}/libschily/mknodat.c"
    "${SCHILY_ROOT}/libschily/mkstemp.c"
    "${SCHILY_ROOT}/libschily/mem.c"
    "${SCHILY_ROOT}/libschily/jmem.c"
    "${SCHILY_ROOT}/libschily/fjmem.c"
    "${SCHILY_ROOT}/libschily/openat.c"
    "${SCHILY_ROOT}/libschily/openat64.c"
    "${SCHILY_ROOT}/libschily/ovstrcpy.c"
    "${SCHILY_ROOT}/libschily/permtostr.c"
    "${SCHILY_ROOT}/libschily/procnameat.c"
    "${SCHILY_ROOT}/libschily/putenv.c"
    "${SCHILY_ROOT}/libschily/raisecond.c"
    "${SCHILY_ROOT}/libschily/readlinkat.c"
    "${SCHILY_ROOT}/libschily/rename.c"
    "${SCHILY_ROOT}/libschily/renameat.c"
    "${SCHILY_ROOT}/libschily/resolvepath.c"
    "${SCHILY_ROOT}/libschily/saveargs.c"
    "${SCHILY_ROOT}/libschily/savewd.c"
    "${SCHILY_ROOT}/libschily/searchinpath.c"
    "${SCHILY_ROOT}/libschily/serrmsg.c"
    "${SCHILY_ROOT}/libschily/seterrno.c"
    "${SCHILY_ROOT}/libschily/setfp.c"
    "${SCHILY_ROOT}/libschily/setnstimeofday.c"
    "${SCHILY_ROOT}/libschily/sleep.c"
    "${SCHILY_ROOT}/libschily/snprintf.c"
    "${SCHILY_ROOT}/libschily/spawn.c"
    "${SCHILY_ROOT}/libschily/strcasecmp.c"
    "${SCHILY_ROOT}/libschily/strncasecmp.c"
    "${SCHILY_ROOT}/libschily/strcasemap.c"
    "${SCHILY_ROOT}/libschily/strcat.c"
    "${SCHILY_ROOT}/libschily/strcatl.c"
    "${SCHILY_ROOT}/libschily/strchr.c"
    "${SCHILY_ROOT}/libschily/strcmp.c"
    "${SCHILY_ROOT}/libschily/strcpy.c"
    "${SCHILY_ROOT}/libschily/strcspn.c"
    "${SCHILY_ROOT}/libschily/strdup.c"
    "${SCHILY_ROOT}/libschily/streql.c"
    "${SCHILY_ROOT}/libschily/strlen.c"
    "${SCHILY_ROOT}/libschily/strlcat.c"
    "${SCHILY_ROOT}/libschily/strlcatl.c"
    "${SCHILY_ROOT}/libschily/strlcpy.c"
    "${SCHILY_ROOT}/libschily/strncat.c"
    "${SCHILY_ROOT}/libschily/strncmp.c"
    "${SCHILY_ROOT}/libschily/strncpy.c"
    "${SCHILY_ROOT}/libschily/strndup.c"
    "${SCHILY_ROOT}/libschily/strnlen.c"
    "${SCHILY_ROOT}/libschily/strrchr.c"
    "${SCHILY_ROOT}/libschily/strspn.c"
    "${SCHILY_ROOT}/libschily/strstr.c"
    "${SCHILY_ROOT}/libschily/swabbytes.c"
    "${SCHILY_ROOT}/libschily/symlinkat.c"
    "${SCHILY_ROOT}/libschily/timegm.c"
    "${SCHILY_ROOT}/libschily/uid.c"
    "${SCHILY_ROOT}/libschily/unlinkat.c"
    "${SCHILY_ROOT}/libschily/uname.c"
    "${SCHILY_ROOT}/libschily/unsetenv.c"
    "${SCHILY_ROOT}/libschily/usleep.c"
    "${SCHILY_ROOT}/libschily/utimens.c"
    "${SCHILY_ROOT}/libschily/utimensat.c"
    "${SCHILY_ROOT}/libschily/vsnprintf.c"
    "${SCHILY_ROOT}/libschily/waitid.c"
    "${SCHILY_ROOT}/libschily/wcscat.c"
    "${SCHILY_ROOT}/libschily/wcscatl.c"
    "${SCHILY_ROOT}/libschily/wcschr.c"
    "${SCHILY_ROOT}/libschily/wcscmp.c"
    "${SCHILY_ROOT}/libschily/wcscpy.c"
    "${SCHILY_ROOT}/libschily/wcscspn.c"
    "${SCHILY_ROOT}/libschily/wcsdup.c"
    "${SCHILY_ROOT}/libschily/wcseql.c"
    "${SCHILY_ROOT}/libschily/wcslen.c"
    "${SCHILY_ROOT}/libschily/wcslcat.c"
    "${SCHILY_ROOT}/libschily/wcslcatl.c"
    "${SCHILY_ROOT}/libschily/wcslcpy.c"
    "${SCHILY_ROOT}/libschily/wcsncat.c"
    "${SCHILY_ROOT}/libschily/wcsncmp.c"
    "${SCHILY_ROOT}/libschily/wcsncpy.c"
    "${SCHILY_ROOT}/libschily/wcsndup.c"
    "${SCHILY_ROOT}/libschily/wcsnlen.c"
    "${SCHILY_ROOT}/libschily/wcsrchr.c"
    "${SCHILY_ROOT}/libschily/wcsspn.c"
    "${SCHILY_ROOT}/libschily/wcsstr.c"
    "${SCHILY_ROOT}/libschily/wctype.c"
    "${SCHILY_ROOT}/libschily/wcastoi.c"
    "${SCHILY_ROOT}/libschily/wdabort.c"
    "${SCHILY_ROOT}/libschily/zerobytes.c"
)
target_include_directories(retrobeam_schily PRIVATE ${RB_NATIVE_COMMON_INCLUDES})
target_compile_definitions(retrobeam_schily PRIVATE
    SCHILY_PRINT
    _FILE_OFFSET_BITS=64
    _GNU_SOURCE
    PORT_ONLY
)
set_target_properties(retrobeam_schily PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)

